name: Publish Docker image

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  docker_push:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: sulir/iostudy
          tags: |
            type=match,pattern=^v(\d.*),group=1
            type=match,pattern=^(?!v\d).*,group=0
            type=ref,event=branch
          labels: org.opencontainers.image.licenses=

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
